Fixture/update config files
dial-once/node-logtify-logentries pull request #8
Opened 2018-08-19 12:45 UTC by steven-heng

Npm audit found 1 low vulnerabilities
Modify rules command of package.json and Makefile

2018-08-20 13:25 UTC, jkernech requested changes

2018-08-20 13:25 UTC, jkernech commented on Makefile
>  	@sonar-scanner-2.8/bin/sonar-runner -e -Dsonar.analysis.mode=publish -Dsonar.host.url=$(SONAR_HOST_URL) -Dsonar.login=$(SONAR_LOGIN) -Dsonar.password=$(SONAR_PASS)
Use `sonar-scanner` rather `sonar-runner` since it's deprecated

2018-09-04 22:05 UTC, jkernech requested changes
Tests need to be fixed

2018-10-16 10:18 UTC, dialonce commented on src/index.js
>    handle(message) {
![CRITICAL](https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL') Refactor this function to reduce its Cognitive Complexity from 19 to the 15 allowed. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.dialonce.net/coding_rules#rule_key=javascript%3AS3776)

2018-10-16 10:18 UTC, dialonce commented
SonarQube analysis reported 1 issue
* ![CRITICAL][CRITICAL] 1 critical

Watch the comments in this conversation to review them.

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'

2018-10-20 10:41 UTC, merged